export const backtestDemo = [
    {
     
      strategyName: "001 Multi bagger 2025",
      version: "v1",
      createdAt: "09/12/2024",
      status: "In Progress",
      timeFrame: "01/12/23 to 01/12/24",
      initialCapital: "₹ 100000",
      avgAnnual: "NA",
      avgGrowth: "NA",
      totalnumber: "NA",
      netProfit: "NA",
      investedPrincipal: "NA",
      maxAccountValue: "NA",
      avgProfitTrade: "NA",
    },
    // Repeated data for demonstration
    {
     
        strategyName: "002 Multi bagger 2025",
      version: "v2",
      createdAt: "09/12/2024",
      status: "In Progress",
      timeFrame: "01/12/23 to 01/12/24",
      initialCapital: "₹ 100000",
      avgAnnual: "NA",
      avgGrowth: "NA",
      totalnumber: "NA",
      netProfit: "NA",
      investedPrincipal: "NA",
      maxAccountValue: "NA",
      avgProfitTrade: "NA",
    },
    {
     
        strategyName: "003 Multi bagger 2025",
      version: "v3",
      createdAt: "09/12/2024",
      status: "Complete",
      timeFrame: "01/12/23 to 01/12/24",
      initialCapital: "₹ 100000",
      avgAnnual: "24%",
      avgGrowth: "24%",
      totalnumber: "NA",
      netProfit: "NA",
      investedPrincipal: "NA",
      maxAccountValue: "NA",
      avgProfitTrade: "NA",
    },
    // Additional rows with completed status
    {
     
        strategyName: "004 Multi bagger 2025",
      version: "v4",
      createdAt: "09/12/2024",
      status: "Complete",
      timeFrame: "01/12/23 to 01/12/24",
      initialCapital: "₹ 100000",
      avgAnnual: "24%",
      avgGrowth: "24%",
      totalnumber: "NA",
      netProfit: "NA",
      investedPrincipal: "NA",
      maxAccountValue: "NA",
      avgProfitTrade: "NA",
    },
    {
     
        strategyName: "005 Multi bagger 2025",
      version: "v5",
      createdAt: "09/12/2024",
      status: "Complete",
      timeFrame: "01/12/23 to 01/12/24",
      initialCapital: "₹ 100000",
      avgAnnual: "24%",
      avgGrowth: "24%",
      totalnumber: "NA",
      netProfit: "NA",
      investedPrincipal: "NA",
      maxAccountValue: "NA",
      avgProfitTrade: "NA",
    },
  ]