const routes = {
  homepage: "/",
  products: "/products",
  termsAndConditions: "/t&c",
  signin: "/signin",
  signup: "/signup",
  logout: "/signout",
  privacyPolicy: "/privacy-policy",
  riskDisclosure: "/risk-disclosure",
  termsgate: "/termsgate",
  additionalDetails: "/additional-details",
  plan: "/plan",
  app: "/app",
  dashboardRoute: "/dashboard",
  backtestRoute: "/Backtest",
  deployRoute: "/Deploy",
  globalRoute: "/Globalfunctions",
  strategiesRoute: "/Strategies",
  strategiesCreateRoute: "/Strategies/create-strategies",
  strategiesEditRoute: "/Strategies/edit-strategies",
  strategiesViewRoute: "/Strategies/view-strategies",
  backtestDetail: "/Backtest/backtest-detail",
  backtestOutput: "/Backtest/backtest-output",
  deployDetail: "/Deploy/deploy-detail",
  plansRoute: "/Plans",
  devStudio: "/Devstudio/create-function",
  editDevStudio: "/Devstudio/edit-function",
  version: "edit-strategies/versions",
  backtestTab: "/edit-strategies/backtest",
};

export default routes;
